name: Version Check and Tag

on:
  push:
    branches:
      - "*"

jobs:
  version_check_and_tag:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Current Versions
        id: set_versions
        run: |
          CURRENT_VERSIONS=""
          for package_json in $(find ./packages -name package.json); do
            version=$(jq -r .version $package_json)
            CURRENT_VERSIONS="${CURRENT_VERSIONS}${version},"
          done
          CURRENT_VERSIONS=${CURRENT_VERSIONS%,} # Remove trailing comma
          echo "CURRENT_VERSIONS=${CURRENT_VERSIONS}" >> $GITHUB_ENV

      - name: Run Version Check and Tag for Each Version
        run: |
          for version in $(echo $CURRENT_VERSIONS | tr ',' ' '); do
            echo "Creating job for version $version..."
            echo "VERSION=${version}" >> $GITHUB_ENV
          done

      - name: Create Release
        run: |
          echo "Running release job for individual tag ${{ steps.set_versions.outputs.version }}"
