pretext: ":warning: {{ actor }} released breaking changes to SDS on the {{ branch }} branch! Library updates newer than version {{ github.event.release.tag_name }} may cause your application to break! :warning:"

text: |
  {{#if payload.commits}}
  *Commits*
  {{#each payload.commits}}
  <{{this.url}}|`{{truncate this.id 8}}`> - {{this.message}}
  {{/each}}
  {{/if}}
footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}
colors:
  default: "#7D3C98"
